### PR TITLE
Native Windows Powershell self-installing client

### PR DESCRIPTION
**Pull request by tevslin**
This client, which runs on Windows 10 and above, uploads data to the Starlink Statuspage website in the same way as the original Linux client which works on Linux, Macs, and Windows with Windows Linux Subsystem (WLS) version 2. It is largely self-installing. Branches should NOT be merged until there is more testing of this client and its install.

### CODE REVIEW

**Comment by Tysonpower** [comment]
is there any Option to test the installer without a connection to Starlink?

**Comment by tevslin** [comment]
No. it might be a good idea. Do you need that to test?

**Comment by Tysonpower** [comment]
Yes, i live in a zone near a radio telescope Starlink isn't allowed to operate, so please add a button "continue anyway" or something to the dialog. I think that will be a good addition :)

**Comment by tevslin** [comment]
I can do this or put in a switch not to query dishy but why would you want data uploaded to Starlink statuspage from people not using Starlink?

 

Thanks

**Comment by Tysonpower** [comment]
Right, a switch would not make sense for non Starlinkusers...mmmm....then just leave it as is, how many People do you know of that tested your installer so far?

**Comment by tevslin** [comment]
I know of four. One had a continuing problem that his download is so remote that speedtest usually failed because of an inability to find test site. One I know is online. The other two I don’t know if they are online or not

**Comment by Tysonpower** [comment]
Can you put all the Installer files into a Folder? Otherwise the main repo will be a bit cluttered. Maybe called "Windows Installer"?

**Comment by tevslin** [comment]
Sure.  Will work on and test over the w/e

**Comment by tevslin** [comment]
I’ll work on that this w/e

**Comment by Tysonpower** [comment]
can i merge it? DId you change the Installer already to my repo?

**Comment by tevslin** [comment]
Just finished. Makes the branch not work by itself so please let me know when I can refer people to the main branch.

 

Thanks.

**Comment by Tysonpower** [comment]
Merged, please test :) Thx for your Work in advance!

**Comment by tevslin** [comment]
Will test now.  I think probably your readme.md or a combined one should come back to the top level of the repository.

**Comment by tevslin** [comment]
I think I’ve fixed in the branch. Can you merge again?

 

Thank you

**Comment by Tysonpower** [comment]
please make a new pull request

**Comment by tevslin** [comment]
done

**Pull request merged**
